<h1><center>Урок 6</center><h1>

### Задание 1
Решите линейную систему:

\begin{equation}\begin{bmatrix}1&2&3\\4&0&6\\7&8&9\end{bmatrix}\cdot X=\begin{bmatrix}12\\2\\1\end{bmatrix}\end{equation}

In [1]:
import numpy as np

In [2]:
M = np.array([[1, 2, 3],
             [4, 0, 6],
             [7, 8, 9]])
M

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [3]:
B = np.array([12, 2, 1])
B

array([12,  2,  1])

In [4]:
S = np.linalg.solve(M, B)
S

array([-9.2       ,  0.9       ,  6.46666667])

In [5]:
np.round(S @ M[0, :])

12.0

In [6]:
np.round(S @ M[1, :])

2.0

In [7]:
np.round(S @ M[2, :])

1.0

### Задание 2
Найдите псевдорешение:<br><br>
$x+2y-z=1$<br>
$3x-4y=7$<br>
$8x-5y+2z=12$<br>
$2x–5z=7$<br>
$11x+4y–7z=15$

In [8]:
M = np.array([[1, 2, -1],
             [3, -4, 0],
             [8, -5, 2],
             [2, 0, -5],
             [11, 4, -7]])
M

array([[ 1,  2, -1],
       [ 3, -4,  0],
       [ 8, -5,  2],
       [ 2,  0, -5],
       [11,  4, -7]])

In [9]:
B = np.array([1, 7, 12, 7, 15])
B

array([ 1,  7, 12,  7, 15])

In [10]:
S = np.linalg.lstsq(M, B, rcond=None)
S

(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

In [11]:
S[0] @ M[0, :]

0.2302049464546464

In [12]:
S[0] @ M[1, :]

7.037518339240224

In [13]:
S[0] @ M[2, :]

11.836509811711325

In [14]:
S[0] @ M[3, :]

6.783288552480718

In [15]:
S[0] @ M[4, :]

15.21805313065206

### Задание 3
Сколько решений имеет линейная система?<br>

\begin{equation}\begin{bmatrix}1&2&3\\4&5&6\\7&8&9\end{bmatrix}\cdot X=\begin{bmatrix}12\\2\\1\end{bmatrix}\end{equation}

Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее.

In [16]:
A = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
B = np.array([[12, 2, 1]])
B

array([[12,  2,  1]])

Определитель равен 0

In [18]:
5*9 - 8*6 - 2*4*9 + 2*7*6 + 3*4*8 - 3*7*5 

0

In [19]:
np.linalg.matrix_rank(A)

2

In [20]:
C = np.hstack([A, B.T])
C

array([[ 1,  2,  3, 12],
       [ 4,  5,  6,  2],
       [ 7,  8,  9,  1]])

Решений нет, т.к. ранг исходной матрицы не совпадает с рангом расишренной

In [21]:
np.linalg.matrix_rank(A), np.linalg.matrix_rank(C)

(2, 3)

Следовательно, чтобы решения были, нужно изменить расширенную матрицу так, чтобы её ранк равнялся 2

Для этого заменим 12 на 3

In [22]:
2*6*1 + 3*2*8 + 5*9*3 - 8*6*3 - 5*3*1 - 9*2*2

0

In [23]:
C[0, 3] = 3

In [24]:
np.linalg.matrix_rank(A), np.linalg.matrix_rank(C)

(2, 2)

In [25]:
C

array([[1, 2, 3, 3],
       [4, 5, 6, 2],
       [7, 8, 9, 1]])

In [26]:
B[0, 0] = 3
B = B[0]
B

array([3, 2, 1])

In [27]:
np.linalg.solve(A, B)

array([ 0.33333333, -4.66666667,  4.        ])

### Задание 4
Вычислите LU-разложение матрицы:

\begin{equation}\begin{bmatrix}1&2&3\\2&16&21\\4&28&73\end{bmatrix}\end{equation}

После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей 

In [28]:
import scipy.linalg

In [29]:
A = np.array([[1, 2, 3],
             [2, 16, 21],
             [4, 28, 73]])

In [30]:
P, L, U = scipy.linalg.lu(A)

In [31]:
print(f'P\n{P}\nL\n{L}\nU\n{U}')

P
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
U
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


\begin{equation}A\cdot X=L\cdot U\cdot X=B\end{equation}

Произвольно зададим B:

In [32]:
B = np.array([4, 5, 7])
B

array([4, 5, 7])

\begin{equation}L\cdot Y=B\end{equation}

\begin{equation}U\cdot X=Y\end{equation}

In [33]:
Y = np.linalg.solve(L, B)
Y

array([4. , 4. , 6.6])

In [34]:
X = np.linalg.solve(U, Y)
X

array([ 5.65277778,  0.13194444, -0.30555556])

In [35]:
np.linalg.solve(A, B)

array([ 4.55555556, -0.11111111, -0.11111111])

Вероятно, разница связана с погрешностью при вычислении

### Задание 5
Найдите нормальное псевдорешение недоопределенной системы:

\begin{equation}\begin{cases}x+2y-z=1\\8x-5y+2z=12\end{cases}\end{equation}

In [51]:
A = np.array([[1, 2, -1],
             [8, -5, 2]])
B = np.array([1, 12])
np.linalg.lstsq(A, B, rcond=-1)

(array([ 1.38191882, -0.18081181,  0.0202952 ]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

### Задание 6
 Найдите одно из псевдорешений вырожденной системы: 


\begin{equation}\begin{bmatrix}1&2&3\\4&5&6\\7&8&9\end{bmatrix}\cdot X =\begin{bmatrix}5\\2\\11\end{bmatrix}\end{equation}

In [77]:
A = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
B = np.array([5, 2, 11])

In [78]:
Q, R = np.linalg.qr(A)

In [79]:
R1 = R[:2, :2]

In [82]:
B1 = (Q.T @ B)[:2]

In [83]:
X1 = np.linalg.solve(R1, B1)

In [87]:
X = np.append(X1, 0)
X

array([-1.,  2.,  0.])